FROM node:12

WORKDIR /usr/src/apps/iot-utils
COPY ./iot-utils/package*.json ./
RUN npm install
COPY ./iot-utils .

WORKDIR /usr/src/apps/iot_db
COPY ./iot_db/package*.json ./
RUN npm install
COPY ./iot_db .

WORKDIR /usr/src/apps/iot_mqtt
COPY ./iot_mqtt/package*.json ./
RUN npm install
COPY ./iot_mqtt .
EXPOSE 1883
CMD [ "npm", "run", "start-dev" ]